import { ParceirosContainer } from "@/components/app/parceiros/ParceirosContainer";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Parceiros | Buridogs",
    description: "Generated by create next app",
};

export default function ParceirosPage() {
    return <ParceirosContainer />;
}
