import { PartnerPage } from "@/components/app/parceiros/PartnerPage";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Parceiros | Buridogs",
    description: "Generated by create next app",
};

export default function ParceirosPage() {
    return <PartnerPage />;
}
