import { Metadata } from "next";
import ContatoContainer from "@/components/app/contato/ContatoContainer";

export const metadata: Metadata = {
    title: "Contato | Buridogs",
    description: "Generated by create next app",
};

export default function ContatoPage() {
    return <ContatoContainer />;
}
