import { Metadata } from "next";

export const metadata: Metadata = {
	title: "Contato | Buridogs",
	description: "Generated by create next app",
};

export default function ContatoPage() {
	return <h1>Contato Page</h1>;
}
