import { Metadata } from "next";

export const metadata: Metadata = {
	title: "Finais Felizes | Buridogs",
	description: "Generated by create next app",
};

export default function FinaisFelizesPage() {
	return <h1>Finais Felizes Page</h1>;
}
