import { Metadata } from "next";
import FinaisFelizesContainer from "@/components/app/finais-felizes/FinaisFelizesContainer";

export const metadata: Metadata = {
    title: "Finais Felizes | Buridogs",
    description: "Generated by create next app",
};

export default function FinaisFelizesPage() {
    return <FinaisFelizesContainer />;
}
