import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Home | Buridogs",
    description: "Generated by create next app",
};

export default function Home() {
    return <h1>Home Page</h1>;
}
