import { AboutUsSection } from "@/components/app/home/AboutUsSection";
import { ContactSection } from "@/components/app/home/ContactSection/ContactSection";
import { HappyEndingSection } from "@/components/app/home/HappyEndingSection/HappyEndingSection";
import { MainSection } from "@/components/app/home/MainSection";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Home | Buridogs",
    description: "Generated by create next app",
};

export default function Home() {
    return (
        <div>
            <MainSection />
            <AboutUsSection />
            <HappyEndingSection />
            <ContactSection />
        </div>
    );
}
