import { Metadata } from "next";

export const metadata: Metadata = {
	title: "Adoção | Buridogs",
	description: "Generated by create next app",
};

export default function AdocaoPage() {
	return <h1>Adoção Page</h1>;
}
