import { Metadata } from "next";
import { AdocaoContainer } from "@/components/app/adocao/AdocaoContainer";

export const metadata: Metadata = {
    title: "Adoção | Buridogs",
    description: "Generated by create next app",
};

export default function AdocaoPage() {
    return <AdocaoContainer />;
}
