import { Metadata } from "next";
import FinaisFelizesDetalhesContainer from "@/components/app/finaisfelizesDetalhes/FinaisFelizesDetalhesContainer";

export const metadata: Metadata = {
    title: "Final Feliz Detalhes | Buridogs",
    description: "Generated by create next app",
};

export default function FinalFelizDetalhes({ params }: { params: { slug: string } }) {
    return <FinaisFelizesDetalhesContainer slug={params.slug} />;
}
