import { Metadata } from "next";

export const metadata: Metadata = {
	title: "Sobre nós | Buridogs",
	description: "Generated by create next app",
};

export default function SobreNosPage() {
	return <h1>Sobre nós Page</h1>;
}
