import { SobreNosContainer } from "@/components/app/sobre-nos/SobreNosContainer";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Sobre nós | Buridogs",
    description: "Generated by create next app",
};

export default function SobreNosPage() {
    return <SobreNosContainer />;
}
